# Generated by Django 4.1 on 2022-08-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('O', 'Open'), ('F', 'Failed'), ('C', 'Completed')], max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id_hitman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hitman')),
            ],
        ),
    ]
